"""add duration_ms to attempts

Revision ID: 7e824bccfb23
Revises: 6ec31525736e
Create Date: 2025-12-11 20:23:30.532909

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e824bccfb23"
down_revision: Union[str, Sequence[str], None] = "6ec31525736e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attempts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attempts",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("total", sa.INTEGER(), nullable=False),
        sa.Column("correct", sa.INTEGER(), nullable=False),
        sa.Column("items", sqlite.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
